.PHONY: generate-values
generate-values:
	@echo "# This file was autogenerated." > charts/kubewarden-controller/values.yaml
	@echo >> charts/kubewarden-controller/values.yaml
	@cat charts/kubewarden-controller/chart-values.yaml >> charts/kubewarden-controller/values.yaml

.PHONY: check-generated-values
check-generated-values: generate-values
	@sh -c 'git diff --exit-code charts || (echo; echo "There are chart differences that have to be checked in"; exit 1)'